[2022-06-06 10:00:11,633] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: data_pipeline.tweets_to_es scheduled__2022-06-06T04:05:00+00:00 [queued]>
[2022-06-06 10:00:11,639] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: data_pipeline.tweets_to_es scheduled__2022-06-06T04:05:00+00:00 [queued]>
[2022-06-06 10:00:11,639] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 10:00:11,639] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-06-06 10:00:11,639] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 10:00:11,650] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): tweets_to_es> on 2022-06-06 04:05:00+00:00
[2022-06-06 10:00:11,653] {standard_task_runner.py:52} INFO - Started process 7803 to run task
[2022-06-06 10:00:11,656] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'tweets_to_es', 'scheduled__2022-06-06T04:05:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/airfow_es.py', '--cfg-path', '/tmp/tmpgv3wfgox', '--error-file', '/tmp/tmplezygzgu']
[2022-06-06 10:00:11,657] {standard_task_runner.py:80} INFO - Job 51: Subtask tweets_to_es
[2022-06-06 10:00:11,689] {task_command.py:370} INFO - Running <TaskInstance: data_pipeline.tweets_to_es scheduled__2022-06-06T04:05:00+00:00 [running]> on host oury-Tp
[2022-06-06 10:00:11,875] {taskinstance.py:1570} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=data_pipeline
AIRFLOW_CTX_TASK_ID=tweets_to_es
AIRFLOW_CTX_EXECUTION_DATE=2022-06-06T04:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-06T04:05:00+00:00
[2022-06-06 10:00:11,878] {twitter.py:696} INFO - Retrieving scroll page None
[2022-06-06 10:00:11,879] {twitter.py:626} INFO - Retrieving guest token
[2022-06-06 10:00:11,882] {base.py:171} INFO - Retrieving https://twitter.com/search?f=live&lang=en&q=near%3ATunis+since%3A1654505711+until%3A1654506011&src=spelling_expansion_revert_click
[2022-06-06 10:00:12,699] {base.py:189} INFO - Retrieved https://twitter.com/search?f=live&lang=en&q=near%3ATunis+since%3A1654505711+until%3A1654506011&src=spelling_expansion_revert_click: 200
[2022-06-06 10:00:12,702] {base.py:171} INFO - Retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=near%3ATunis+since%3A1654505711+until%3A1654506011&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel
[2022-06-06 10:00:13,572] {base.py:189} INFO - Retrieved https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=near%3ATunis+since%3A1654505711+until%3A1654506011&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel: 200
[2022-06-06 10:00:13,950] {logging_mixin.py:115} INFO - {'id': 1533735006551658497, 'username': 'FLASHMAGtn', 'tweet_date': datetime.datetime(2022, 6, 6, 8, 58, 15, tzinfo=datetime.timezone.utc), 'tweet_content': 'Quel visage pour la raie au milieu\xa0? https://t.co/eVbpFk4LMi', 'likes_count': 0, 'tweet_url': 'https://twitter.com/FLASHMAGtn/status/1533735006551658497', 'tweet_lang': 'fr'}
[2022-06-06 10:00:13,952] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/oury/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/oury/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/oury/airflow/dags/airfow_es.py", line 49, in tweet_to_es_func
    index_es_func(tweets_index, tweet)
TypeError: index_es_func() missing 1 required positional argument: 'tweet'
[2022-06-06 10:00:13,955] {taskinstance.py:1396} INFO - Marking task as FAILED. dag_id=data_pipeline, task_id=tweets_to_es, execution_date=20220606T040500, start_date=20220606T090011, end_date=20220606T090013
[2022-06-06 10:00:13,963] {standard_task_runner.py:92} ERROR - Failed to execute job 51 for task tweets_to_es (index_es_func() missing 1 required positional argument: 'tweet'; 7803)
[2022-06-06 10:00:13,995] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-06 10:00:14,010] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-06-06 10:40:33,725] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: data_pipeline.tweets_to_es scheduled__2022-06-06T04:05:00+00:00 [queued]>
[2022-06-06 10:40:33,733] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: data_pipeline.tweets_to_es scheduled__2022-06-06T04:05:00+00:00 [queued]>
[2022-06-06 10:40:33,733] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 10:40:33,733] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-06-06 10:40:33,733] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 10:40:33,745] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): tweets_to_es> on 2022-06-06 04:05:00+00:00
[2022-06-06 10:40:33,748] {standard_task_runner.py:52} INFO - Started process 15958 to run task
[2022-06-06 10:40:33,752] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'tweets_to_es', 'scheduled__2022-06-06T04:05:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/airfow_es.py', '--cfg-path', '/tmp/tmpsntim943', '--error-file', '/tmp/tmpqscrhzqb']
[2022-06-06 10:40:33,753] {standard_task_runner.py:80} INFO - Job 51: Subtask tweets_to_es
[2022-06-06 10:40:33,789] {task_command.py:370} INFO - Running <TaskInstance: data_pipeline.tweets_to_es scheduled__2022-06-06T04:05:00+00:00 [running]> on host oury-Tp
[2022-06-06 10:40:33,836] {taskinstance.py:1570} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=data_pipeline
AIRFLOW_CTX_TASK_ID=tweets_to_es
AIRFLOW_CTX_EXECUTION_DATE=2022-06-06T04:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-06T04:05:00+00:00
[2022-06-06 10:40:33,837] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/oury/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/oury/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: tweet_to_es_func() missing 5 required positional arguments: 'es', 'start', 'end', 'location', and 'languages'
[2022-06-06 10:40:33,840] {taskinstance.py:1396} INFO - Marking task as FAILED. dag_id=data_pipeline, task_id=tweets_to_es, execution_date=20220606T040500, start_date=20220606T094033, end_date=20220606T094033
[2022-06-06 10:40:33,851] {standard_task_runner.py:92} ERROR - Failed to execute job 51 for task tweets_to_es (tweet_to_es_func() missing 5 required positional arguments: 'es', 'start', 'end', 'location', and 'languages'; 15958)
[2022-06-06 10:40:33,884] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-06 10:40:33,901] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
