[2022-06-06 09:58:31,332] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: data_pipeline.tweets_to_es scheduled__2022-06-06T02:10:00+00:00 [queued]>
[2022-06-06 09:58:31,343] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: data_pipeline.tweets_to_es scheduled__2022-06-06T02:10:00+00:00 [queued]>
[2022-06-06 09:58:31,343] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 09:58:31,343] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-06-06 09:58:31,343] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 09:58:31,355] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): tweets_to_es> on 2022-06-06 02:10:00+00:00
[2022-06-06 09:58:31,357] {standard_task_runner.py:52} INFO - Started process 7001 to run task
[2022-06-06 09:58:31,360] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'tweets_to_es', 'scheduled__2022-06-06T02:10:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/airfow_es.py', '--cfg-path', '/tmp/tmpnoan43oc', '--error-file', '/tmp/tmptd5w92_t']
[2022-06-06 09:58:31,361] {standard_task_runner.py:80} INFO - Job 28: Subtask tweets_to_es
[2022-06-06 09:58:31,392] {task_command.py:370} INFO - Running <TaskInstance: data_pipeline.tweets_to_es scheduled__2022-06-06T02:10:00+00:00 [running]> on host oury-Tp
[2022-06-06 09:58:31,440] {taskinstance.py:1570} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=data_pipeline
AIRFLOW_CTX_TASK_ID=tweets_to_es
AIRFLOW_CTX_EXECUTION_DATE=2022-06-06T02:10:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-06T02:10:00+00:00
[2022-06-06 09:58:31,441] {twitter.py:696} INFO - Retrieving scroll page None
[2022-06-06 09:58:31,441] {twitter.py:626} INFO - Retrieving guest token
[2022-06-06 09:58:31,443] {base.py:171} INFO - Retrieving https://twitter.com/search?f=live&lang=en&q=near%3ATunis+since%3A1654505611+until%3A1654505911&src=spelling_expansion_revert_click
[2022-06-06 09:58:31,973] {base.py:189} INFO - Retrieved https://twitter.com/search?f=live&lang=en&q=near%3ATunis+since%3A1654505611+until%3A1654505911&src=spelling_expansion_revert_click: 200
[2022-06-06 09:58:31,976] {base.py:171} INFO - Retrieving https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=near%3ATunis+since%3A1654505611+until%3A1654505911&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel
[2022-06-06 09:58:32,516] {base.py:189} INFO - Retrieved https://api.twitter.com/2/search/adaptive.json?include_profile_interstitial_type=1&include_blocking=1&include_blocked_by=1&include_followed_by=1&include_want_retweets=1&include_mute_edge=1&include_can_dm=1&include_can_media_tag=1&skip_status=1&cards_platform=Web-12&include_cards=1&include_ext_alt_text=true&include_quote_count=true&include_reply_count=1&tweet_mode=extended&include_entities=true&include_user_entities=true&include_ext_media_color=true&include_ext_media_availability=true&send_error_codes=true&simple_quoted_tweets=true&q=near%3ATunis+since%3A1654505611+until%3A1654505911&tweet_search_mode=live&count=100&query_source=spelling_expansion_revert_click&pc=1&spelling_corrections=1&ext=mediaStats%2ChighlightedLabel: 200
[2022-06-06 09:58:32,887] {logging_mixin.py:115} INFO - {'id': 1533735006551658497, 'username': 'FLASHMAGtn', 'tweet_date': datetime.datetime(2022, 6, 6, 8, 58, 15, tzinfo=datetime.timezone.utc), 'tweet_content': 'Quel visage pour la raie au milieu\xa0? https://t.co/eVbpFk4LMi', 'likes_count': 0, 'tweet_url': 'https://twitter.com/FLASHMAGtn/status/1533735006551658497', 'tweet_lang': 'fr'}
[2022-06-06 09:58:32,890] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/oury/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/oury/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/oury/airflow/dags/airfow_es.py", line 49, in tweet_to_es_func
    index_es_func(tweets_index, tweet)
TypeError: index_es_func() missing 1 required positional argument: 'tweet'
[2022-06-06 09:58:32,893] {taskinstance.py:1396} INFO - Marking task as FAILED. dag_id=data_pipeline, task_id=tweets_to_es, execution_date=20220606T021000, start_date=20220606T085831, end_date=20220606T085832
[2022-06-06 09:58:32,902] {standard_task_runner.py:92} ERROR - Failed to execute job 28 for task tweets_to_es (index_es_func() missing 1 required positional argument: 'tweet'; 7001)
[2022-06-06 09:58:32,937] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-06 09:58:32,953] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-06-06 10:38:48,923] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: data_pipeline.tweets_to_es scheduled__2022-06-06T02:10:00+00:00 [queued]>
[2022-06-06 10:38:48,934] {taskinstance.py:1160} INFO - Dependencies all met for <TaskInstance: data_pipeline.tweets_to_es scheduled__2022-06-06T02:10:00+00:00 [queued]>
[2022-06-06 10:38:48,934] {taskinstance.py:1357} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 10:38:48,934] {taskinstance.py:1358} INFO - Starting attempt 1 of 1
[2022-06-06 10:38:48,934] {taskinstance.py:1359} INFO - 
--------------------------------------------------------------------------------
[2022-06-06 10:38:49,333] {taskinstance.py:1378} INFO - Executing <Task(PythonOperator): tweets_to_es> on 2022-06-06 02:10:00+00:00
[2022-06-06 10:38:49,338] {standard_task_runner.py:52} INFO - Started process 15236 to run task
[2022-06-06 10:38:49,342] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'data_pipeline', 'tweets_to_es', 'scheduled__2022-06-06T02:10:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/airfow_es.py', '--cfg-path', '/tmp/tmpcqpgjegs', '--error-file', '/tmp/tmpapw_hpr8']
[2022-06-06 10:38:49,343] {standard_task_runner.py:80} INFO - Job 28: Subtask tweets_to_es
[2022-06-06 10:38:50,330] {task_command.py:370} INFO - Running <TaskInstance: data_pipeline.tweets_to_es scheduled__2022-06-06T02:10:00+00:00 [running]> on host oury-Tp
[2022-06-06 10:38:52,599] {taskinstance.py:1570} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=data_pipeline
AIRFLOW_CTX_TASK_ID=tweets_to_es
AIRFLOW_CTX_EXECUTION_DATE=2022-06-06T02:10:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-06T02:10:00+00:00
[2022-06-06 10:38:52,601] {taskinstance.py:1890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/oury/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/oury/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: tweet_to_es_func() missing 5 required positional arguments: 'es', 'start', 'end', 'location', and 'languages'
[2022-06-06 10:38:52,633] {taskinstance.py:1396} INFO - Marking task as FAILED. dag_id=data_pipeline, task_id=tweets_to_es, execution_date=20220606T021000, start_date=20220606T093848, end_date=20220606T093852
[2022-06-06 10:38:53,168] {standard_task_runner.py:92} ERROR - Failed to execute job 28 for task tweets_to_es (tweet_to_es_func() missing 5 required positional arguments: 'es', 'start', 'end', 'location', and 'languages'; 15236)
[2022-06-06 10:38:53,210] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-06 10:38:53,227] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
